[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Ryan Carins <ryan.carins@riscy.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
image = "0.23"
